### PR TITLE
Added assert statements for tests

### PR DESCRIPTION
**Pull request by murthyvijay**
1. Tests now include dependency and skip tags
2. Added assert statements to ensure false positives are not overlooked

### CODE REVIEW

**Review by chrispsommers — CHANGES_REQUESTED** [review]
This branch is not synced to main. main contains a new directory `test/test-cases/functional/saic` and your tests should live there. Please first sync to main, then change the directory for `sai-api` accordingly.

**Comment by murthyvijay** [comment]
> This branch is not synced to main. main contains a new directory `test/test-cases/functional/saic` and your tests should live there. Please first sync to main, then change the directory for `sai-api` accordingly.

I resolved all merge conflicts and now it looks to be in sync with main and the checks seemed to pass. Now should my scripts go directly to saic or should I create another directory sai-api and move them there? If there are going to be different flavors of functional tests then I would prefer to add a new directory called sai-api. Please let me know.

**Comment by murthyvijay** [comment]
I see that some remove API operation return 0 while others return -1. Do we know what is the standard behavior?

**Comment by chrispsommers** [comment]
> > This branch is not synced to main. main contains a new directory `test/test-cases/functional/saic` and your tests should live there. Please first sync to main, then change the directory for `sai-api` accordingly.
> 
> I resolved all merge conflicts and now it looks to be in sync with main and the checks seemed to pass. Now should my scripts go directly to saic or should I create another directory sai-api and move them there? If there are going to be different flavors of functional tests then I would prefer to add a new directory called sai-api. Please let me know.

Just move the sai-api directory under functional instead of under scale. Sorry I was not clear.

**Comment by chrispsommers** [comment]
> I see that some remove API operation return 0 while others return -1. Do we know what is the standard behavior?

Return code should be 0. -1 indicates failure.
The proper assert coding pattern for non-create cases is as follows. I though I'd already shown this in another review, maybe it got dropped:
```
        results = [*dpu.process_commands( (self.make_remove_commands()) )] # Or whatever your commands look like
        print("\n======= SAI commands RETURN values =======")
        assert all( [result == 0 for result in results]), "Remove error" # This verifies every result == 0
        print(results)
```

**Pull request closed without merging**
